// All CV content lives here. Add/edit entries and both UI languages update.
// Bump this whenever content changes — it drives the "Last Update" footer line.
const LAST_UPDATE = "2026-09-04";

const UI = {
  en: {
    profile: "Professional Profile",
    skills: "Skills",
    experience: "Work Experience",
    projects: "Industrial Projects",
    education: "Education",
    teaching: "Teaching Experience",
    conferences: "Conferences and Presentations",
    awards: "Awards",
    patents: "Patents",
    publications: "Publications and Proceedings",
    services: "Academic Services",
    international: "International",
    domestic: "Domestic",
    intlJournal: "International Journal (SCI & SCIE & SSCI)",
    domJournal: "Domestic Journal (KCI)",
    workingPapers: "Working Papers",
    selectedProjects: "Selected Projects",
    lastUpdate: "Last Update",
    notes: "(a) alphabetically ordered (equally contributed) · (c) corresponding author · (f) first author · * equal contribution",
  },
  kr: {
    profile: "소개",
    skills: "보유 역량",
    experience: "경력",
    projects: "산업 프로젝트",
    education: "학력",
    teaching: "강의 경력",
    conferences: "학술발표",
    awards: "수상",
    patents: "특허",
    publications: "논문 및 출판물",
    services: "학술 활동",
    international: "국제",
    domestic: "국내",
    intlJournal: "국제 저널 (SCI & SCIE & SSCI)",
    domJournal: "국내 저널 (KCI)",
    workingPapers: "작업 중인 논문",
    selectedProjects: "주요 프로젝트",
    lastUpdate: "최종 수정일",
    notes: "(a) 알파벳 순 (균등 기여) · (c) 교신저자 · (f) 제1저자 · * 균등 기여",
  },
};

const PROFILE = {
  name: "NohYoon Seong",
  email: "nyseong94@gmail.com",
  scholar: "https://scholar.google.com/citations?user=m7w57hoAAAAJ&hl=ko",
  photo: "assets/photo.png",
  summary: {
    en: ["Management Information System (MIS)", "Machine Learning and Deep Learning for Business and Finance"],
    kr: ["경영정보시스템(MIS)", "비즈니스·금융을 위한 머신러닝 및 딥러닝"],
  },
};

const SKILLS = {
  en: ["Python programming for Machine Learning and Deep Learning", "R programming & C++ programming", "Econometrics"],
  kr: ["머신러닝/딥러닝을 위한 Python 프로그래밍", "R 프로그래밍 & C++ 프로그래밍", "계량경제학"],
};

// Each entry: period, role {en,kr}, org, location, bullets {en,kr}[]
const EXPERIENCE = [
  {
    period: "Feb. 2022 ~",
    role: { en: "CEO", kr: "대표(CEO)" },
    org: { en: "A.I.mtory", kr: "(주)아임토리" },
    location: "Seoul",
    bullets: [{ en: "AI for Smart Factory", kr: "스마트팩토리를 위한 AI" }],
    projectList: [
      {
        org: { en: "Risk Consulting Korea", kr: "리스크컨설팅코리아" },
        name: { en: "News interpretation: information classification & summarization", kr: "뉴스해석: 정보 분류 및 요약" },
        period: "Jan. 2026 ~",
      },
      {
        org: { en: "Donghwa Entec", kr: "동화엔텍" },
        name: { en: "Quote (estimate) information extraction", kr: "견적서 정보 추출" },
        period: "Dec. 2025 ~",
      },
      {
        org: { en: "Hanwha Ocean", kr: "한화오션" },
        name: { en: "Ship block assembly status tracking algorithm using a 3D exterior inspection platform", kr: "3D 외관 검수 플랫폼을 이용한 선박 소조 조립 현황 파악 알고리즘" },
        period: "May. 2025 ~ Dec. 2025",
      },
      {
        org: { en: "Donghwa Entec", kr: "동화엔텍" },
        name: { en: "Consulting", kr: "컨설팅" },
        period: "Oct. 2024 ~ Dec. 2024",
      },
      {
        org: { en: "Hansol Paper", kr: "한솔제지" },
        name: { en: "AI-based incinerator operating pattern analysis and control-point prediction by operating standard", kr: "AI 기술을 활용한 소각로 운전 패턴 분석 및 운영 기준별 제어 시점 예측" },
        period: "Oct. 2024 ~ Mar. 2025",
      },
      {
        org: { en: "SG Global (Sindong Plant)", kr: "SG글로벌 신동사업장" },
        name: { en: "Vision inspection system", kr: "비전검사기" },
        period: "Oct. 2024 ~ Nov. 2024",
        note: { en: "subscription from Oct. 2025", kr: "2025년 10월부터 구독 중" },
      },
      {
        org: "LS ITC",
        name: { en: "LQC", kr: "LQC" },
        period: "May. 2024 ~ Sep. 2024",
      },
      {
        org: "KM&I",
        name: { en: "Vision system", kr: "비전시스템" },
        period: "Dec. 2023 ~ Jun. 2024",
        note: { en: "subscription from Feb. 2025", kr: "2025년 2월부터 구독 중" },
      },
      {
        org: { en: "KM&I (Changwon Plant)", kr: "KM&I 창원공장" },
        name: { en: "Consulting", kr: "컨설팅 (창원공장)" },
        period: "Oct. 2023 ~ Dec. 2023",
      },
      {
        org: { en: "Kyobo Information & Communication", kr: "교보정보통신" },
        name: { en: "Advisory retainer", kr: "자문" },
        period: "Jun. 2023 ~ Dec. 2023",
      },
      {
        org: { en: "Hyundai NGV", kr: "현대엔지비" },
        name: { en: "Hyundai vehicle robot condition-based monitoring (CBM)", kr: "현차 로봇 CBM" },
        period: "Jan. 2023 ~ Nov. 2023",
      },
      {
        org: { en: "LS Electric", kr: "LS일렉트릭" },
        name: { en: "Robot process optimization", kr: "로봇 공정 최적화" },
        period: "Oct. 2022 ~ Jan. 2023",
      },
    ],
    note: { en: "Served as Project Manager (PM) for all A.I.mtory projects listed above.", kr: "위 A.I.mtory 프로젝트는 모두 PM(프로젝트 매니저)으로 수행." },
  },
  {
    period: "Feb. 2023 ~",
    role: { en: "Instructor", kr: "강사" },
    org: { en: "Korea National Open University", kr: "한국방송통신대학교" },
    location: "Seoul",
    bullets: [{ en: "Computer Vision", kr: "컴퓨터 비전" }],
  },
  {
    period: "Mar. 2022 ~ Feb. 2023",
    role: { en: "Instructor", kr: "강사" },
    org: { en: "KyungHee University", kr: "경희대학교" },
    location: "Seoul",
    bullets: [
      { en: "Management Information Systems", kr: "경영정보시스템" },
      { en: "Programming Language and Data Science", kr: "프로그래밍 언어 및 데이터 과학" },
    ],
  },
  {
    period: "Oct. 2021 ~ Oct. 2022",
    role: { en: "AI Programmer", kr: "AI 프로그래머" },
    org: { en: "Basbai", kr: "바스바이" },
    location: "Seoul",
    bullets: [
      { en: "Computer Vision for fracture detection", kr: "골절 진단을 위한 컴퓨터 비전" },
      { en: "Deep learning for cancer prediction with genetic sequence", kr: "유전자 서열 기반 암 예측 딥러닝" },
    ],
  },
  {
    period: "Oct. 2020 ~ Apr. 2021",
    role: { en: "AI Programmer", kr: "AI 프로그래머" },
    org: { en: "Fashionade", kr: "패션에이드" },
    location: "Seoul",
    bullets: [{ en: "Fashion compatibility prediction with computer vision", kr: "컴퓨터 비전 기반 패션 조합 적합성 예측" }],
  },
  {
    period: "Jan. 2020 ~ Mar. 2021",
    role: { en: "AI Programmer", kr: "AI 프로그래머" },
    org: { en: "Animal Industry Data Korea", kr: "한국축산데이터" },
    location: "Seoul",
    bullets: [
      { en: "Computer Vision and Reinforcement Learning for object detection, multi-object tracking, and re-identification of livestock", kr: "가축 객체 탐지, 다중 객체 추적, 재식별을 위한 컴퓨터 비전 및 강화학습" },
      { en: "Pose estimation", kr: "자세 추정(Pose Estimation)" },
    ],
  },
];

const PROJECTS = [
  {
    period: "Apr. 2020 ~ Dec. 2020",
    role: { en: "Data Scientist", kr: "데이터 사이언티스트" },
    org: { en: "KB Financial Group", kr: "KB금융그룹" },
    location: "Seoul",
    bullets: [
      { en: "Reinforcement learning for portfolio optimization", kr: "포트폴리오 최적화를 위한 강화학습" },
      { en: "Deep learning for stock prediction and market analysis", kr: "주가 예측 및 시장 분석 딥러닝" },
    ],
  },
  {
    period: "Jul. 2019 ~ Dec. 2019",
    role: { en: "Project Manager (DEER LAB)", kr: "프로젝트 매니저 (DEER LAB)" },
    org: "PopFunding",
    bullets: [
      { en: "Developing AI model to evaluate accounts receivable and for risk management", kr: "매출채권 평가 및 리스크 관리를 위한 AI 모델 개발" },
      { en: "Optimizing LTV and interest rate for accounts receivable financing", kr: "매출채권 금융을 위한 LTV 및 금리 최적화" },
      { en: "Deep learning based credit score prediction", kr: "딥러닝 기반 신용점수 예측" },
    ],
  },
  {
    period: "Oct. 2019 ~ Nov. 2019",
    role: { en: "Data Scientist", kr: "데이터 사이언티스트" },
    org: {
      en: "Big Data Academy Education TA & ML Project, Samsung Fire & Marine Insurance",
      kr: "빅데이터 아카데미 교육 조교 및 머신러닝 프로젝트, 삼성화재해상보험",
    },
    orgNote: { en: "Kookmin University Industry-Academia Collaboration Foundation", kr: "국민대학교 산학협력단" },
    location: "Seoul",
    bullets: [
      { en: "Deep learning for settlement amount prediction", kr: "보험금 지급액 예측 딥러닝" },
      { en: "Deep learning for insurance recommender system", kr: "보험 추천 시스템 딥러닝" },
      { en: "Deep learning for anomaly detection in accounting", kr: "회계 이상탐지 딥러닝" },
    ],
  },
  {
    period: "Jun. ~ Sep. 2019",
    role: { en: "Data Scientist", kr: "데이터 사이언티스트" },
    org: { en: "AfreecaTV", kr: "아프리카TV" },
    location: "Seoul",
    bullets: [
      { en: "Text mining for user chatting analysis", kr: "사용자 채팅 분석을 위한 텍스트 마이닝" },
      { en: "Voice recognition and speech analysis", kr: "음성 인식 및 음성 분석" },
      { en: "Meta-data generation from chatting and speech analysis", kr: "채팅·음성 분석 기반 메타데이터 생성" },
    ],
  },
  {
    period: "Feb. ~ Jul. 2019",
    role: { en: "Data Scientist", kr: "데이터 사이언티스트" },
    org: { en: "Recommender System, Samsung C&T – SSF SHOP", kr: "추천 시스템, 삼성물산 – SSF샵" },
    orgNote: { en: "Hansung University Industry-Academia Collaboration Foundation", kr: "한성대학교 산학협력단" },
    location: "Seoul",
    bullets: [
      { en: "Machine Learning and Deep Learning for Personalized Recommendation", kr: "개인화 추천을 위한 머신러닝 및 딥러닝" },
      { en: "Successful A/B test against Recopick, the industry's 1st recommender system", kr: "업계 1위 추천 시스템 Recopick 대비 A/B 테스트 성공" },
    ],
  },
  {
    period: "Nov. 2018 ~ Apr. 2019",
    role: { en: "Project Manager (DEER LAB)", kr: "프로젝트 매니저 (DEER LAB)" },
    org: "2digits",
    bullets: [
      { en: "Developing next-generation securities valuation, future value prediction, and risk management model based on artificial intelligence", kr: "AI 기반 차세대 증권 가치평가·미래가치 예측·리스크 관리 모델 개발" },
      { en: "Deep learning based cryptocurrency volatility prediction", kr: "딥러닝 기반 암호화폐 변동성 예측" },
      { en: "Extension of stock loan model to evaluate cryptocurrency loans with liquidation and stochastic volatility", kr: "청산 및 확률적 변동성을 반영한 암호화폐 대출 평가로 주식담보대출 모델 확장" },
    ],
  },
  {
    period: "Oct. 2018 ~ Nov. 2018",
    role: { en: "Data Scientist", kr: "데이터 사이언티스트" },
    org: {
      en: "Big Data Academy Education TA & ML Project, Samsung Fire & Marine Insurance",
      kr: "빅데이터 아카데미 교육 조교 및 머신러닝 프로젝트, 삼성화재해상보험",
    },
    orgNote: { en: "Kookmin University Industry-Academia Collaboration Foundation", kr: "국민대학교 산학협력단" },
    location: "Seoul",
    bullets: [
      { en: "Deep learning survival model for Risk Consultant churn prediction", kr: "리스크 컨설턴트 이탈 예측을 위한 생존분석 딥러닝 모델" },
      { en: "Sequence model to analyze system status and predict errors from core system log data", kr: "핵심 시스템 로그 기반 시스템 상태 분석 및 오류 예측 시퀀스 모델" },
    ],
  },
  {
    period: "Aug. 2018 ~ Sep. 2018",
    role: { en: "Researcher (DEER LAB)", kr: "연구원 (DEER LAB)" },
    org: { en: "Korea Blockchain Association", kr: "한국블록체인협회" },
    bullets: [
      { en: "Analysis of employment effectiveness of blockchain technology", kr: "블록체인 기술의 고용 효과성 분석" },
      { en: "Scenario planning", kr: "시나리오 플래닝" },
      { en: "Interview", kr: "인터뷰" },
    ],
  },
  {
    period: "Apr. ~ Sep. 2018",
    role: { en: "Data Scientist", kr: "데이터 사이언티스트" },
    org: { en: "Recommender System, Samsung C&T – SSF SHOP", kr: "추천 시스템, 삼성물산 – SSF샵" },
    orgNote: { en: "Hansung University Industry-Academia Collaboration Foundation", kr: "한성대학교 산학협력단" },
    location: "Seoul",
    bullets: [
      { en: "Machine Learning and Deep Learning for Product Recommendation", kr: "상품 추천을 위한 머신러닝 및 딥러닝" },
      { en: "Successful A/B test against Recopick, the industry's 1st recommender system", kr: "업계 1위 추천 시스템 Recopick 대비 A/B 테스트 성공" },
      { en: "Customer segmentation using user-item embedding and deep learning", kr: "사용자-아이템 임베딩 및 딥러닝 기반 고객 세분화" },
      { en: "Econometrics for customer analysis and customer cube", kr: "고객 분석 및 고객 큐브를 위한 계량경제학" },
    ],
  },
  {
    period: "Nov. 2017 ~ Dec. 2017",
    role: { en: "Data Scientist", kr: "데이터 사이언티스트" },
    org: {
      en: "Big Data Academy Education TA & ML Project, Samsung Fire & Marine Insurance",
      kr: "빅데이터 아카데미 교육 조교 및 머신러닝 프로젝트, 삼성화재해상보험",
    },
    orgNote: { en: "Kookmin University Industry-Academia Collaboration Foundation", kr: "국민대학교 산학협력단" },
    location: "Seoul",
    bullets: [
      { en: "Website revisit prediction model with LSTM on log data", kr: "로그 데이터 기반 LSTM 웹사이트 재방문 예측 모델" },
      { en: "Insurance coverage recommender system with Deep Neural Network", kr: "심층신경망 기반 보험 보장 추천 시스템" },
    ],
  },
  {
    period: "Jul. 2017 ~ Dec. 2017",
    role: { en: "Researcher (DEER LAB)", kr: "연구원 (DEER LAB)" },
    org: { en: "NICE Investors Service", kr: "나이스신용평가" },
    bullets: [{ en: "An empirical study on financial market, credit infrastructure, and economic growth", kr: "금융시장·신용인프라·경제성장에 관한 실증연구" }],
  },
  {
    period: "Jul. 2017 ~ Dec. 2017",
    role: { en: "Data Scientist", kr: "데이터 사이언티스트" },
    org: { en: "Sentience", kr: "센티언스" },
    location: "Seoul",
    bullets: [
      { en: "Web crawling", kr: "웹 크롤링" },
      { en: "Text mining – fake news detection", kr: "텍스트 마이닝 – 가짜뉴스 탐지" },
      { en: "Business data analysis", kr: "비즈니스 데이터 분석" },
    ],
  },
  {
    period: "Jul. 2017 ~ Nov. 2017",
    role: { en: "Researcher (DEER LAB)", kr: "연구원 (DEER LAB)" },
    org: { en: "KAIST 4th Industrial Revolution Research Project", kr: "KAIST 4차산업혁명 연구프로젝트" },
    bullets: [{ en: "Robot industry and labor markets", kr: "로봇 산업과 노동시장" }],
  },
];

const EDUCATION = [
  {
    period: "2017.02 – 2022.02",
    degree: { en: "Ph.D. in Management Information Systems", kr: "경영정보시스템 박사" },
    org: { en: "Management Information Science, KAIST College of Business", kr: "경영정보학, KAIST 경영대학" },
    location: "Seoul",
  },
  {
    period: "2015.02 – 2015.06",
    degree: { en: "Exchange Student in Grandes Écoles", kr: "그랑제콜 교환학생" },
    org: "École Centrale Paris",
    location: "",
  },
  {
    period: "2012.02 – 2017.02",
    degree: { en: "Bachelor of Physics", kr: "물리학 학사" },
    org: { en: "Korea Advanced Institute of Science and Technology (KAIST)", kr: "한국과학기술원(KAIST)" },
    location: "Daejeon",
  },
];

// Each entry: period, role {en,kr} (course name), org {en,kr}, location, bullets {en,kr}[], note {en,kr}
const TEACHING = [
  {
    period: "2023 ~ 2026 (Spring)",
    role: { en: "Instructor", kr: "강사" },
    org: { en: "Korea National Open University", kr: "한국방송통신대학교" },
    location: "Seoul",
    bullets: [
      { en: "Computer Vision — 16-week course, offered every Spring term", kr: "컴퓨터비전 — 매 봄학기 16주 과정" },
      { en: "Week 1: CV Introduction — Introduction of CV", kr: "1주차: CV 개론 — 컴퓨터 비전 소개" },
      { en: "Week 2: Convolutional Networks (1) — Basics of CNNs", kr: "2주차: 합성곱 신경망 (1) — CNN 기초" },
      { en: "Week 3: Convolutional Networks (2) — Basics of CNNs and modern CNNs", kr: "3주차: 합성곱 신경망 (2) — CNN 기초 및 최신 CNN" },
      { en: "Week 4: Object Detection (1) — Object recognition, detection, segmentation", kr: "4주차: 객체 탐지 (1) — 객체 인식·탐지·분할" },
      { en: "Week 5: Object Detection (2) — Object recognition, detection, segmentation", kr: "5주차: 객체 탐지 (2) — 객체 인식·탐지·분할" },
      { en: "Week 6: Object Detection (3) — Object recognition, detection, segmentation", kr: "6주차: 객체 탐지 (3) — 객체 인식·탐지·분할" },
      { en: "Week 7: Recurrent Neural Networks — Review of RNNs, CNN+RNN models", kr: "7주차: 순환 신경망 — RNN 복습, CNN+RNN 모델" },
      { en: "Week 8: Attention Models (1) — Attention models in vision", kr: "8주차: 어텐션 모델 (1) — 비전에서의 어텐션 모델" },
      { en: "Week 9: Attention Models (2) — Transformer in vision", kr: "9주차: 어텐션 모델 (2) — 비전에서의 트랜스포머" },
      { en: "Week 10: Anomaly Detection", kr: "10주차: 이상 탐지" },
      { en: "Week 11: Deep Generative Models (1) — VAE, GAN, PixelRNN", kr: "11주차: 딥 생성 모델 (1) — VAE, GAN, PixelRNN" },
      { en: "Week 12: Deep Generative Models (2) — Applications (image editing, inpainting, super-resolution)", kr: "12주차: 딥 생성 모델 (2) — 응용 (이미지 편집, 인페인팅, 초해상도)" },
      { en: "Week 13: Reinforcement Learning and Computer Vision", kr: "13주차: 강화학습과 컴퓨터비전" },
      { en: "Week 14: Recent Trends — Zero-shot, one-shot, few-shot learning, self-supervised learning", kr: "14주차: 최신 동향 — 제로샷·원샷·퓨샷 학습, 자기지도학습" },
      { en: "Week 15: Real-World Applications — Data collection, preprocessing, training, evaluation, MLOps", kr: "15주차: 실전 응용 — 데이터 수집, 전처리, 학습, 평가, MLOps" },
    ],
    note: { en: "Also conducted 6 hands-on lab sessions per term.", kr: "학기당 실습 특강 6회 별도 진행." },
  },
  {
    period: "2023 Fall",
    role: { en: "Instructor", kr: "강사" },
    org: { en: "KyungHee University", kr: "경희대학교" },
    location: "Seoul",
    bullets: [
      { en: "Introduction to MIS", kr: "경영정보시스템(개론)" },
      { en: "Business Programming", kr: "경영프로그래밍" },
    ],
  },
  {
    period: "2022 Spring",
    role: { en: "Instructor", kr: "강사" },
    org: { en: "KyungHee University", kr: "경희대학교" },
    location: "Seoul",
    bullets: [{ en: "Introduction to MIS", kr: "경영정보시스템(개론)" }],
  },
];

// Citations kept in original submitted language across both UI languages (academic convention).
const CONFERENCES = {
  international: [
    "NohYoon Seong, Keongtae Kim. “Equity Crowdfunding and Startup Performance.” International Conference on Information Systems (ICIS) (2021). (Conference, presenter) (f)",
    "NohYoon Seong, Kihwan Nam. “Deep learning for financial distress prediction considering individual effect and complex system.” SIGKDD Machine Learning in Finance Workshop (2021). (Conference, presenter) (f)",
    "NohYoon Seong, Kihwan Nam. “Neural recommender system considering user homogeneity.” SIGKDD Machine Learning for Consumers and Markets Workshop (2021). (Conference, presenter) (f)",
    "NohYoon Seong, Keongtae Kim. “Equity Crowdfunding and Startup Performance.” 81th Annual Meeting of the Academy of Management (AOM) (2021). (Conference, presenter) (f)",
    "Jooyoung Kim, NohYoon Seong, Kihwan Nam. “Better than Humans? AI challenge in Creative Tasks: Randomized Field Experiment on AI Recommender Systems.” INFORMS Workshop on Data Science (2020). (Conference)",
    "NohYoon Seong, Kihwan Nam, Byungtae Lee. “Predicting stock movements based on financial news with systematic group identification.” INFORMS Workshop on Data Science (2020). (Conference) (f)",
    "NohYoon Seong, Kihwan Nam, Byungtae Lee. “Deep learning for financial distress prediction considering individual effect and complex system.” INFORMS Workshop on Data Science (2020). (Conference, Best student paper nominee) (f)",
    "Jooyoung Kim, NohYoon Seong, Kihwan Nam. “Better than Humans? AI challenge in Creative Tasks: Randomized Field Experiment on AI Recommender Systems.” Conference on Information Systems and Technology (CIST) (2020). (Conference)",
    "KiHwan Nam, Hyelin Oh, Wonseok Oh, NohYoon Seong. “A “Falsely-Framed” Choice: A Randomized Field Experiment on the Attraction Effects in Recommender Systems.” Conference on Information Systems and Technology (CIST) (2020). (Conference)",
    "Keongtae Kim, NohYoon Seong, Viswanathan Siva. “Impact of Equity Crowdfunding on Venture Performance.” Statistical Challenges in Electronic Commerce Research (SCECR) (2020). Madrid, Spain (Conference, presenter) (a)",
    "SangMyung Lee, NohYoon Seong. “Existence and Time Trend of Psychological Barrier in Bitcoin Market: Evidence from US, Europe, Hong Kong.” International Conference on Information Systems (ICIS) (2019). Munich, Germany (Conference) (c)",
    "Jooman Kim, Gloria Jinakim, Nohyoon Seong, Taeyong Yang. “The Effect of the Price Fluctuation of Cryptocurrency and Personal Characteristics on Technology Acceptance of Cryptocurrency by Medical Service Providers.” Korean Chapter of the Association for Information Systems (KrAIS) (2018). San Francisco, USA (Conference, presenter)",
  ],
  domestic: [
    "KiHwan Nam, Hyelin Oh, Wonseok Oh, NohYoon Seong. “A “Falsely-Framed” Choice: A Randomized Field Experiment on the Attraction Effects in Recommender Systems.” KMIS, 2019 Fall. (Conference, Best Paper Award (2nd)) (a)",
    "NohYoon Seong, KiHwan Nam. “Predicting stock movements based on financial news with systematic group identification.” Korea Intelligent Information System Society, 2019 Spring. Seoul, Republic of Korea (Conference, Presenter) (f)",
    "“Blockchain Strategy Management Research Proposal Award.” Korean Strategic Management Information (Award/$2,500)",
    "KiHwan Nam, WooChang Jeong, NohYoon Seong. “Prediction of blockbuster drama with a pattern analysis on early viewing ratings.” Korea Intelligent Information System Society, 2018 Spring. Seoul, Republic of Korea (Conference) (c)",
    "NohYoon Seong, KiHwan Nam. “Online news-based stock price forecasting considering homogeneity in the sector.” Korea Intelligent Information System Society, 2017 Fall. Seoul, Republic of Korea (Conference, Presenter) (f)",
    "NohYoon Seong, KiHwan Nam. “Combining macro-economical effects with sentiment analysis for stock index prediction.” Korea Intelligent Information System Society, 2017 Spring. Seoul, Republic of Korea (Conference, Presenter) (f)",
  ],
};

const AWARDS = [
  {
    period: "2023.12.30",
    role: { en: "Certificate of Commendation", kr: "표창장" },
    org: { en: "Seoul Metropolitan Government", kr: "서울특별시" },
    bullets: [{ en: "Seoul R&D Support Program — Artificial Intelligence", kr: "서울형 R&D 지원사업 — 인공지능 부문" }],
  },
  {
    period: "2023.12.22",
    role: { en: "R&D Innovation Grand Prize", kr: "R&D 혁신분야 대상" },
    org: { en: "Money Today", kr: "머니투데이" },
    bullets: [{ en: "2023 Korea Enterprise Awards — Smart Factory AI Solution", kr: "2023 대한민국 기업대상 — 스마트팩토리 AI 솔루션 부문" }],
  },
  {
    period: "2023.03.31",
    role: { en: "Certificate of Completion", kr: "수료증" },
    org: { en: "Incheon National University Startup Support Center", kr: "인천대학교 창업지원단" },
    bullets: [{ en: "2022 Early-Stage Startup Package", kr: "2022 초기창업패키지" }],
  },
  {
    period: "2023.03.31",
    role: { en: "Excellence Award", kr: "우수상" },
    org: { en: "Incheon National University Startup Support Center", kr: "인천대학교 창업지원단" },
    bullets: [{ en: "2022 Early-Stage Startup Package", kr: "2022 초기창업패키지" }],
  },
  {
    period: "2022.12.27",
    role: { en: "R&D Innovation Grand Prize", kr: "R&D 혁신분야 대상" },
    org: { en: "Money Today", kr: "머니투데이" },
    bullets: [{ en: "2022 Korea Enterprise Awards — Smart Factory AI Solution", kr: "2022 대한민국 기업대상 — 스마트팩토리 AI 솔루션 부문" }],
  },
  {
    period: "2022.12.14",
    role: { en: "Startup Grand Prize", kr: "스타트업 최우수상" },
    org: { en: "Korea Gas Corporation (KOGAS)", kr: "한국가스공사" },
    bullets: [{ en: "4th Big Data Startup Competition — BOG (Boil-Off Gas) Optimal Operation Prediction", kr: "제4회 빅데이터 스타트업 경진대회 — BOG 최적가동 예측 부문" }],
  },
  {
    period: "2022.12.07",
    role: { en: "3rd Place", kr: "3위" },
    org: { en: "Korea Institute of Startup & Entrepreneurship Development (KISED)", kr: "창업진흥원" },
    bullets: [{ en: "Big-Star Solver Platform", kr: "대-스타 해결사 플랫폼" }],
  },
];

const PUBLICATIONS = {
  intlJournal: [
    "JunKyu Jang, NohYoon Seong. (2023) “Deep reinforcement learning for stock portfolio optimization by connecting with modern portfolio theory.” Expert Systems with Applications, 218, 119556 (c)",
    "NohYoon Seong, KiHwan Nam. (2022) “Forecasting price movements of global financial indexes using complex quantitative financial networks.” Knowledge-Based Systems, 235, 107608 (f)",
    "NohYoon Seong. (2021). “Deep spatiotemporal attention network for fine particle matter 2.5 concentration prediction with causality analysis.” IEEE Access, 9, 73230–73239 (c, f)",
    "NohYoon Seong, KiHwan Nam. (2021). “Predicting stock movements based on financial news and market segmentation.” Expert Systems with Applications, 164, 113988 (f)",
    "KiHwan Nam, NohYoon Seong. (2021). “A Study on Influencing Factors for Customer Satisfaction and the Continuing Use of Social Network Services in Financial Industry.” Enterprise Information Systems, 15(3), 395–419 (c)",
    "KiHwan Nam, NohYoon Seong. (2019). “Financial news-based stock price prediction using causality analysis of influence in the Korean stock market.” Decision Support Systems, 117, 100–112 (c)",
  ],
  domJournal: [
    "NohYoon Seong, KiHwan Nam. (2019). “Predicting stock movements based on financial news with systematic group identification.” Journal of Intelligence and Information Systems, 25(3), 1–17 (f)",
    "KiHwan Nam, NohYoon Seong. (2018). “Prediction of a hit drama with a pattern analysis on early viewing ratings.” Journal of Intelligence and Information Systems, 24(4), 33–49 (c)",
    "NohYoon Seong, KiHwan Nam. (2018). “Online news-based stock price forecasting considering homogeneity in the sector.” Journal of Intelligence and Information Systems, 24(2), 1–19 (f)",
    "NohYoon Seong, KiHwan Nam. (2017) “Combining macro-economical effects with sentiment analysis for stock index prediction.” Entrue Journal of Information Technology, 16(2), 41–54 (f)",
  ],
  workingPapers: [
    "NohYoon Seong, Youngchan Hwang, JooYoung Kim, Keongtae Kim, Sunil Mithas. (2023) “Balancing Expertise: How Equity Crowdfunding and Investor Composition Affect Startup Performance.” MIS Quarterly, Major Revision (f)",
    "NohYoon Seong, Kanghyun Cho, KiHwan Nam. “Beyond Persuasion: Communication Style as a Buffer Against Market Volatility in Inclusive Decentralized Fundraising.” Journal of Business Research, Major Revision (c)",
    "KiHwan Nam, Wonseok Oh, NohYoon Seong. “Frame of Mind: A Validation of Attraction Effects in Recommender Systems Through a Randomized Field Experiment.” Production and Operations Management, Major Revision (a)",
    "SangMyung Lee, NohYoon Seong. “Existence and Time Trend of Psychological Barrier in Bitcoin Market: Evidence from US, Europe, Hong Kong.” (c)",
    "Jooyoung Kim, NohYoon Seong, Kihwan Nam. “Better than Humans? AI challenge in Creative Tasks: Randomized Field Experiment on AI Recommender Systems.”",
    "NohYoon Seong, KiHwan Nam. “Predicting stock movements based on financial news with systematic group identification.” (f)",
  ],
};

const PATENTS = [
  {
    title: { en: "Device and method for data detection using computer vision technology", kr: "컴퓨터 비전 기술을 활용한 데이터 검출 장치 및 방법" },
    number: "10-2900777",
    date: "2025.12.11",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Device and method for anomaly detection using unsupervised learning", kr: "비지도 학습을 활용한 이상 패턴 감지 장치 및 방법" },
    number: "10-2819231",
    date: "2025.06.05",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "System for providing robot camera data based three dimentional transformation service", kr: "로봇의 카메라 데이터 기반 3D 변환 서비스 제공 시스템" },
    number: "10-2813943",
    date: "2025.05.23",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["성노윤", "남기환"],
  },
  {
    title: { en: "Apparatus and method for controlling robot movements using digital twin", kr: "디지털 트윈을 이용한 로봇의 움직임 제어 장치 및 방법" },
    number: "10-2808178",
    date: "2025.05.12",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["성노윤", "남기환"],
  },
  {
    title: { en: "Apparatus and method for automated robot teaching considering multiple robot movements", kr: "다수의 로봇 동작을 고려한 자동화 로봇 티칭 장치 및 방법" },
    number: "10-2800409",
    date: "2025.04.21",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Device and method for teaching computer vision-based robotic arm", kr: "컴퓨터 비전을 활용한 로봇팔 티칭 장치 및 방법" },
    number: "10-2800405",
    date: "2025.04.21",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Data processing device and method for factory management", kr: "공장 관리를 위한 데이터 처리 장치 및 방법" },
    number: "10-2800401",
    date: "2025.04.21",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Device and method for robot motion detection using 3d digital spatial technology", kr: "3D 환경의 디지털 공간기술을 이용한 로봇 움직임 감지 장치 및 방법" },
    number: "10-2792859",
    date: "2025.04.03",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["성노윤", "남기환"],
  },
  {
    title: { en: "Ai-based robot arm image data processing method", kr: "인공지능 기반의 로봇 팔 이미지 데이터 처리 방법" },
    number: "10-2770773",
    date: "2025.02.17",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Multimodal data processing system and device in smart factory", kr: "스마트팩토리의 멀티모달 데이터 처리 시스템 및 전자 장치" },
    number: "10-2769420",
    date: "2025.02.13",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Method for abnormal operation sensing of robot arm", kr: "인공지능 기반의 로봇팔의 이상 동작 센싱 방법" },
    number: "10-2766865",
    date: "2025.02.07",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Apparatus and method for attribute generation of structured data for machine learning", kr: "머신 러닝을 위한 정형 데이터 속성 생성 장치 및 방법" },
    number: "10-2748907",
    date: "2024.12.26",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["성노윤", "남기환"],
  },
  {
    title: { en: "Method and device for providing fuel efficiency optimization solutions based on ship operations data", kr: "선박 운용 데이터 기반의 연비 최적화 솔루션 제공 방법 및 장치" },
    number: "10-2747608",
    date: "2024.12.23",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["김태환", "남기환", "성노윤", "이병석"],
  },
  {
    title: { en: "Methods and apparatus for monitoring cavitation in ship propellers", kr: "선박 프로펠러의 캐비테이션 모니터링 방법 및 장치" },
    number: "10-2742470",
    date: "2024.12.10",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["김태환", "남기환", "성노윤", "이병석"],
  },
  {
    title: { en: "Device and method for providing behavior improvement solution of smart factory", kr: "스마트 팩토리의 행동개선 솔루션을 제공하는 장치 및 방법" },
    number: "10-2709710",
    date: "2024.09.20",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Method and device for controlling ship operation through ship engine data learning", kr: "선박 엔진 데이터 학습을 통한 선박 운행 제어 방법 및 장치" },
    number: "10-2681535",
    date: "2024.07.01",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["유건우", "남기환", "성노윤", "이병석"],
  },
  {
    title: { en: "Apparatus and method for monitoring and artificial intelligence prediction of engine cylinder temperature of ship", kr: "선박의 엔진 실린더 온도 모니터링 및 인공지능 예측 방법 및 장치" },
    number: "10-2675460",
    date: "2024.06.11",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["유건우", "남기환", "성노윤", "이병석"],
  },
  {
    title: { en: "System for providing time-series data based data sampling service", kr: "시계열 데이터 기반 데이터 샘플링 서비스 제공 시스템" },
    number: "10-2647331",
    date: "2024.03.08",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["성노윤", "남기환"],
  },
  {
    title: { en: "Apparatus and method for data augmentation and data analysis", kr: "데이터 증식 및 분석 장치 및 방법" },
    number: "10-2647337",
    date: "2024.03.08",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["성노윤", "남기환"],
  },
  {
    title: { en: "System for providing two dimensional and three dimensional matching service for robot", kr: "로봇 기반 2D 및 3D 매칭 서비스 제공 시스템" },
    number: "10-2624242",
    date: "2024.01.09",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["성노윤", "남기환"],
  },
  {
    title: { en: "Robot status diagnostics device and method using robot axis motion prediction model", kr: "로봇 축 움직임 예측 모델을 통한 로봇 상태 진단 장치 및 방법" },
    number: "10-2624240",
    date: "2024.01.09",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["이병석", "남기환", "성노윤"],
  },
  {
    title: { en: "Domain adaptation device and method for robot arm", kr: "로봇팔의 도메인 적응 장치 및 방법" },
    number: "10-2624237",
    date: "2024.01.09",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["성노윤", "남기환"],
  },
  {
    title: { en: "Method and apparatus for reducing vibration noise in a robot arm", kr: "로봇팔의 진동 노이즈 제거 방법 및 장치" },
    number: "10-2607486",
    date: "2023.11.24",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Apparatus and method for analysising motion of ergonomic-based humanoid robots", kr: "인체공학 기반의 휴머노이드 로봇의 모션 분석방법 및 장치" },
    number: "10-2607490",
    date: "2023.11.24",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Apparatus and method for analysising motion of robots", kr: "로봇의 모션 분석 방법 및 장치" },
    number: "10-2607493",
    date: "2023.11.24",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Method and apparatus for reducing noise in a robot arm", kr: "로봇팔의 노이즈 제거 방법 및 장치" },
    number: "10-2607487",
    date: "2023.11.24",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "System for providing smartfactory based safety distance maintenance service using collaborative robot trajectory analysis", kr: "스마트팩토리 기반 협동로봇 궤적 분석을 이용한 안전거리 확보 서비스 제공 시스템" },
    number: "10-2594983",
    date: "2023.10.24",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Method and apparatus for optimizing of robot process", kr: "교착 지점의 딜레이 보상 기능을 갖는 로봇 공정 최적화 방법 및 장치" },
    number: "10-2595007",
    date: "2023.10.24",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "System for providing vision based data synchronization service between collaborative robot", kr: "비전 기반 협업로봇 간 데이터 동기화 서비스 제공 시스템" },
    number: "10-2567743",
    date: "2023.08.11",
    status: "registered",
    applicant: { en: "A.I.mtory", kr: "(주)아임토리" },
    inventors: ["남기환", "성노윤"],
  },
  {
    title: { en: "Playing back section moving apparatus using learning", kr: "학습을 통한 화장법 영상 구간 이동 장치" },
    number: "10-2318394",
    date: "2021.10.21",
    status: "lapsed",
    applicant: { en: "TheBalla", kr: "(주)더발라" },
    inventors: ["남기환", "임관령", "성노윤"],
  },
];


const SERVICES = [
  { en: "Peer Review in ICIS", kr: "ICIS 논문 심사" },
  { en: "Peer Review in Decision Support Systems", kr: "Decision Support Systems 논문 심사" },
  { en: "Peer Review in Journal of Intelligence and Information Systems", kr: "Journal of Intelligence and Information Systems 논문 심사" },
];
